### ISSUE TITLE
TaskData examples

### ISSUE THREAD

**Issue by Deniskovv** [axelande/pyAgriculture11783#1]
Hello!
I'm looking for various examples of real work in ISO-XML format to debug my code.
Can you help me with examples of planting and harvesting data?
Please send to deniskovv@gmail.com. Or post some examples in this repository for general use ...
Thanks!

**Comment by axelande** [comment]
Have you had a look in the Combiner/TaskData and Potatoes/TaskData folders? There are some examples of harvesting data.

/Axel
